### ISSUE TITLE
Can't install, error on gulp pack:osx64

### ISSUE THREAD

**Issue by mgroth0** [Sytten/Facebook-Messenger-Desktop#65]
running on OSX 10.12.3. The aluxian version worked fine, but I checked this one out and noticed you could hide the sidebar so I wanted to get this. I did not reinstall any dependencies or make any other changes because I figured that installation is the same as aluxian/Messenger.

~/D/Facebook-Messenger-Desktop   master   gulp pack:osx64                            I 
[02:19:06] Failed to load external module coffee-script/register
[02:19:06] Failed to load external module coffee-script
/Users/Matt/Documents/Facebook-Messenger-Desktop/gulpfile.coffee:1
(function (exports, require, module, __filename, __dirname) { gulp = require 'gulp'
                                                                             ^^^^^^
SyntaxError: Unexpected string
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)

**Comment by Sytten** [comment]
Its the V1, the new V2 of aluxian uses Electron instead of NWJS...
So probably a problem with dependencies.
I have stopped working on it the V1 anyway...

**Comment by mgroth0** [comment]
I see, thank you for clarifying.
