### ISSUE TITLE
Error when checking for updates

### ISSUE THREAD

**Issue by Kezarious** [Sytten/Facebook-Messenger-Desktop#66]
I'm using Linux Mint 18, and I get the following error when I load up the messenger app, I'm not sure what's causing it but it just started happening in the past few days:

`Javascript Error in main process
TypeError: Invalid Version: undefined
    at new SemVer (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:279:11)
    at compare (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:595:10)
    at /opt/messengerfordesktop/resources/app.asar/scripts/browser/components/auto-updater/base.js:79:49
    at done (/opt/messengerfordesktop/resources/app.asar/node_modules/needle/lib/needle.js:432:14)
    at PassThrough.<anonymous> (/opt/messengerfordesktop/resources/app.asar/node_modules/needle/lib/needle.js:671:11)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by Sytten** [comment]
I stopped working on the project a while ago, I suggest you try https://github.com/sindresorhus/caprine
